---
- hosts: servers
  become: true
  tasks:
  - name: start the container
    docker_container:
      name: xyz-app
      image: ngwaabanjong/xyz-app
      state: started
      published_ports:
        - 0.0.0.0:8000:8000


# make sure pip is installed on servers (docker-py) too