apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyz-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xyz-v1
      version: v1
  template:
    metadata:
      labels:
        app: xyz-v1
        version: v1
    spec:
      containers:
        - image: ngwaabanjong/xyz-app
          imagePullPolicy: Always
          name: hostname
          resources:
            limits:
              cpu: 256m
              memory: 128Mi
      nodeSelector:
        nodetype: generalpurpose

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xyz-v1
  name: xyz-v1
spec:
  ports:
    - name: web
      port: 61000
      protocol: TCP
      targetPort: 61000
  selector:
    app: xyz-v1
